"""add user.words_today, user.words_update_time

Revision ID: 219a29d60f0d
Revises: 7b5df128884d
Create Date: 2016-10-01 22:15:18.038929

"""

# revision identifiers, used by Alembic.
revision = '219a29d60f0d'
down_revision = '7b5df128884d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('words_today', sa.PickleType(), nullable=True))
    op.add_column('users', sa.Column('words_update_time', sa.DateTime(), nullable=True))
    op.drop_column('users', 'lask_seen')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lask_seen', mysql.DATETIME(), nullable=True))
    op.drop_column('users', 'words_update_time')
    op.drop_column('users', 'words_today')
    op.drop_column('users', 'last_seen')
    ### end Alembic commands ###
