"""add user.task_complied

Revision ID: 426eccf49d27
Revises: 219a29d60f0d
Create Date: 2016-10-03 10:31:50.568790

"""

# revision identifiers, used by Alembic.
revision = '426eccf49d27'
down_revision = '219a29d60f0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('task_complied', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'task_complied')
    ### end Alembic commands ###
