"""add word.example_sentence

Revision ID: 94ea62f45e32
Revises: 3131c80cdbcb
Create Date: 2016-10-05 12:15:59.221198

"""

# revision identifiers, used by Alembic.
revision = '94ea62f45e32'
down_revision = '3131c80cdbcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words', sa.Column('example_sentence', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'example_sentence')
    ### end Alembic commands ###
